spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
  redis:
    host: 192.168.0.14
    port: 6379
logging:
  level:
    root: WARN
    com:
      hly: DEBUG



